backend:
  name: github
  repo: ryancoughlin/beyond-the-fly

media_folder: static/assets
public_folder: assets

collections:
  - name: story
    label: Story
    folder: story
    create: true
    fields:
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Title", name: "title", widget: "text"}
      - {label: "Introduction", name: "introduction", widget: "string"}
      - label: "First Section"
        name: "first_section"
        widget: "object"
        fields:
          - {label: "Title", name: "text", widget: "string"}
          - {label: "Body", name: "text", widget: "text"}
          - {label: "Featured Image", name: "featured_image", widget: "image"}


      - {label: "Full Width Image", name: "full_width_image", widget: "image"}
      - {label: "Full Width Image", name: "thumbnail", widget: "image"}
      
      - label: "Tiled Image Gallery"
        name: "tiled_image_gallery"
        widget: "object"
        fields:
          - {label: "Image", name: "featured_image", widget: "image"}
          - {label: "Image", name: "featured_image", widget: "image"}
          - {label: "Image", name: "featured_image", widget: "image"}
          - {label: "Image", name: "featured_image", widget: "image"}
          - {label: "Image", name: "featured_image", widget: "image"}
